# Use a lightweight image
FROM ubuntu:24.04

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    tar \
    git \
    perl \
    bowtie2 \
    samtools \
    default-jre \
    cutadapt \
    fastqc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create a non-root user (e.g., 'defaultuser')
RUN useradd -m -s /bin/bash defaultuser && \
    mkdir -p /home/methylation/tools /home/methylation/data /home/methylation/output /home/methylation/genomes && \
    chown -R defaultuser:defaultuser /home/methylation

# Set working directory
WORKDIR /home/methylation/tools

# Install CGmapTools
RUN git clone https://github.com/guoweilong/cgmaptools.git && \
    cd cgmaptools && \
    chmod +x install.sh && \
    ./install.sh && \
    echo "export PATH=$(pwd):\$PATH" >> ~/.bash_profiles && \
    source ~/.bash_profiles

# Install TrimGalore!
RUN curl -fsSL https://github.com/FelixKrueger/TrimGalore/archive/0.6.10.tar.gz -o trim_galore.tar.gz && \
    tar xvzf trim_galore.tar.gz && \
    mv TrimGalore-* TrimGalore && \
    chmod -R u+rwx TrimGalore && \
    chown -R defaultuser:defaultuser TrimGalore && \
    ln -s /home/methylation/tools/TrimGalore/trim_galore /usr/local/bin/trim_galore

# Install Bismark
RUN curl -fsSL https://github.com/FelixKrueger/Bismark/archive/refs/tags/v0.24.2.tar.gz -o Bismark.tar.gz && \
    tar xvzf Bismark.tar.gz && \
    mv Bismark-* Bismark && \
    chmod -R u+rwx Bismark && \
    chown -R defaultuser:defaultuser Bismark && \
    ln -s /home/methylation/tools/Bismark/bismark /usr/local/bin/bismark && \
    ln -s /home/methylation/tools/Bismark/bismark_methylation_extractor /usr/local/bin/bismark_methylation_extractor && \
    ln -s /home/methylation/tools/Bismark/bismark_genome_preparation /usr/local/bin/bismark_genome_preparation

# Set working directory
WORKDIR /home/methylation/

# Switch to the non-root user
USER defaultuser

# Set default command
# CMD ["bash", "run_pipeline.sh", "/home/methylation/data/...", "-o", "/home/methylation/output", "-g", "/home/methylation/data/NCBI_genome"]
ENTRYPOINT ["bash", "bismark_pipeline.sh"]
