name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    name: Build and push images to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.pipeline
          push: true
          tags: mzouari974/methylation-pipeline:latest

      - name: Build and Push Processing Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.processing
          push: true
          tags: mzouari974/methylation-processing:latest
